import {
  ArrowsClockwiseIcon,
  BarbellIcon,
  PersonSimpleRunIcon,
} from "@phosphor-icons/react"
import type { SplitConfig } from "@/features/training/types"

export const UPPER_LOWER_SPLIT: SplitConfig = {
  type: "upper-lower",
  label: "Superior / Inferior",
  weekModes: ["upper-lower-4"],
  workouts: [
    {
      splitType: "upper-lower",
      type: "upper-a",
      label: "Superior A",
      title: "Superior A (Tensão)",
      icon: BarbellIcon,
      badge: "FORÇA / COMPOSTOS",
      focus: "strength",
      duration: "65-85 min",
      exercises: [
        {
          name: "Supino Reto (Barra)",
          detail: "Peito",
          type: "COMPOSTO",
          muscleGroup: "chest",
          setsReps: "3 × 5-7",
          defaultSets: 3,
          rest: "3 min",
          notes: "RIR alvo 2.",
        },
        {
          name: "Remada Curvada",
          detail: "Costas",
          type: "COMPOSTO",
          muscleGroup: "back",
          setsReps: "3 × 6-8",
          defaultSets: 3,
          rest: "2-3 min",
          notes: "RIR alvo 2.",
        },
        {
          name: "Desenvolvimento Militar",
          detail: "Ombros",
          type: "COMPOSTO",
          muscleGroup: "shoulders",
          setsReps: "3 × 6-8",
          defaultSets: 3,
          rest: "2 min",
          notes: "Core ativo.",
        },
        {
          name: "Barra Fixa",
          detail: "Costas",
          type: "COMPOSTO",
          muscleGroup: "back",
          setsReps: "3 × 6-10",
          defaultSets: 3,
          rest: "2 min",
          notes: "Adicionar carga quando possível.",
        },
        {
          name: "Tríceps Paralelas",
          detail: "Tríceps",
          type: "ISOLAMENTO",
          muscleGroup: "triceps",
          setsReps: "3 × 8-12",
          defaultSets: 3,
          rest: "90 s",
          notes: "RIR alvo 1.",
        },
      ],
    },
    {
      splitType: "upper-lower",
      type: "lower-a",
      label: "Inferior A",
      title: "Inferior A (Tensão)",
      icon: PersonSimpleRunIcon,
      badge: "FORÇA / COMPOSTOS",
      focus: "strength",
      duration: "65-85 min",
      exercises: [
        {
          name: "Agachamento Livre",
          detail: "Quadríceps",
          type: "COMPOSTO",
          muscleGroup: "quads",
          setsReps: "3 × 5-7",
          defaultSets: 3,
          rest: "3 min",
          notes: "RIR alvo 2.",
        },
        {
          name: "Levantamento Terra Romeno",
          detail: "Posterior",
          type: "COMPOSTO",
          muscleGroup: "hamstrings",
          setsReps: "3 × 8-10",
          defaultSets: 3,
          rest: "2-3 min",
          notes: "Alongamento máximo.",
        },
        {
          name: "Leg Press",
          detail: "Quadríceps",
          type: "COMPOSTO",
          muscleGroup: "quads",
          setsReps: "3 × 10-12",
          defaultSets: 3,
          rest: "2 min",
          notes: "Sem travar joelhos.",
        },
        {
          name: "Cadeira Extensora",
          detail: "Quadríceps",
          type: "ISOLAMENTO",
          muscleGroup: "quads",
          setsReps: "3 × 12-15",
          defaultSets: 3,
          rest: "60-90 s",
          notes: "Pausa no topo.",
        },
      ],
    },
    {
      splitType: "upper-lower",
      type: "upper-b",
      label: "Superior B",
      title: "Superior B (Volume)",
      icon: ArrowsClockwiseIcon,
      badge: "HIPERTROFIA",
      focus: "hypertrophy",
      duration: "65-85 min",
      exercises: [
        {
          name: "Supino Inclinado (Halteres)",
          detail: "Peito superior",
          type: "COMPOSTO",
          muscleGroup: "chest",
          setsReps: "4 × 8-10",
          defaultSets: 4,
          rest: "2 min",
          notes: "RIR alvo 1-2.",
        },
        {
          name: "Remada Sentada",
          detail: "Costas",
          type: "COMPOSTO",
          muscleGroup: "back",
          setsReps: "4 × 8-12",
          defaultSets: 4,
          rest: "90 s",
          notes: "Contração no final.",
        },
        {
          name: "Elevação Lateral",
          detail: "Deltoide lateral",
          type: "ISOLAMENTO",
          muscleGroup: "shoulders",
          setsReps: "3 × 12-20",
          defaultSets: 3,
          rest: "60 s",
          notes: "Sem impulso.",
        },
        {
          name: "Rosca Direta",
          detail: "Bíceps",
          type: "ISOLAMENTO",
          muscleGroup: "biceps",
          setsReps: "3 × 8-12",
          defaultSets: 3,
          rest: "60-90 s",
          notes: "Amplitude total.",
        },
        {
          name: "Tríceps Corda",
          detail: "Tríceps",
          type: "ISOLAMENTO",
          muscleGroup: "triceps",
          setsReps: "3 × 10-15",
          defaultSets: 3,
          rest: "60-90 s",
          notes: "Controle excêntrico.",
        },
      ],
    },
    {
      splitType: "upper-lower",
      type: "lower-b",
      label: "Inferior B",
      title: "Inferior B (Volume)",
      icon: PersonSimpleRunIcon,
      badge: "HIPERTROFIA",
      focus: "hypertrophy",
      duration: "65-85 min",
      exercises: [
        {
          name: "Agachamento Frontal",
          detail: "Quadríceps",
          type: "COMPOSTO",
          muscleGroup: "quads",
          setsReps: "4 × 6-10",
          defaultSets: 4,
          rest: "2-3 min",
          notes: "Postura alta.",
        },
        {
          name: "Stiff com Halteres",
          detail: "Posterior",
          type: "COMPOSTO",
          muscleGroup: "hamstrings",
          setsReps: "3 × 8-12",
          defaultSets: 3,
          rest: "2 min",
          notes: "Alongamento controlado.",
        },
        {
          name: "Afundo Caminhando",
          detail: "Glúteos e quads",
          type: "COMPOSTO",
          muscleGroup: "glutes",
          setsReps: "3 × 10-12",
          defaultSets: 3,
          rest: "90 s",
          notes: "Passo estável.",
        },
        {
          name: "Mesa Flexora",
          detail: "Posterior",
          type: "ISOLAMENTO",
          muscleGroup: "hamstrings",
          setsReps: "3 × 12-15",
          defaultSets: 3,
          rest: "60-90 s",
          notes: "Pico de contração.",
        },
        {
          name: "Panturrilha em Pé",
          detail: "Panturrilha",
          type: "ISOLAMENTO",
          muscleGroup: "calves",
          setsReps: "4 × 10-15",
          defaultSets: 4,
          rest: "45-60 s",
          notes: "Pausa no alongamento.",
        },
      ],
    },
  ],
}
