import {
  ArrowsClockwiseIcon,
  BarbellIcon,
  PersonSimpleRunIcon,
} from "@phosphor-icons/react"
import type { SplitConfig } from "@/features/training/types"

export const PPL_SPLIT: SplitConfig = {
  type: "ppl",
  label: "Empurrar / Puxar / Pernas",
  weekModes: ["ppl-6", "ppl-3"],
  workouts: [
    {
      splitType: "ppl",
      type: "push",
      label: "Empurrar",
      title: "Empurrar",
      icon: BarbellIcon,
      badge: "PEITO / OMBRO / TRÍCEPS",
      focus: "hypertrophy",
      duration: "70-90 min",
      exercises: [
        {
          name: "Supino Reto (Barra)",
          detail: "Peito completo",
          type: "COMPOSTO",
          muscleGroup: "chest",
          setsReps: "4 × 6-8",
          defaultSets: 4,
          rest: "2-3 min",
          notes: "Controle na descida, acelere na subida.",
        },
        {
          name: "Supino Inclinado (Halteres)",
          detail: "Peito superior",
          type: "COMPOSTO",
          muscleGroup: "chest",
          setsReps: "3 × 8-10",
          defaultSets: 3,
          rest: "90 s",
          notes: "Amplitude completa.",
        },
        {
          name: "Desenvolvimento Militar",
          detail: "Deltoide global",
          type: "COMPOSTO",
          muscleGroup: "shoulders",
          setsReps: "3 × 6-8",
          defaultSets: 3,
          rest: "2 min",
          notes: "Evite hiperextensão lombar.",
        },
        {
          name: "Elevação Lateral",
          detail: "Deltoide lateral",
          type: "ISOLAMENTO",
          muscleGroup: "shoulders",
          setsReps: "3 × 10-15",
          defaultSets: 3,
          rest: "60 s",
          notes: "Sem balanço.",
        },
        {
          name: "Tríceps Corda",
          detail: "Tríceps",
          type: "ISOLAMENTO",
          muscleGroup: "triceps",
          setsReps: "3 × 10-12",
          defaultSets: 3,
          rest: "60-90 s",
          notes: "Cotovelos estáveis.",
        },
      ],
    },
    {
      splitType: "ppl",
      type: "pull",
      label: "Puxar",
      title: "Puxar",
      icon: ArrowsClockwiseIcon,
      badge: "COSTAS / BÍCEPS",
      focus: "hypertrophy",
      duration: "70-90 min",
      exercises: [
        {
          name: "Barra Fixa",
          detail: "Dorsal",
          type: "COMPOSTO",
          muscleGroup: "back",
          setsReps: "4 × 6-10",
          defaultSets: 4,
          rest: "2-3 min",
          notes: "Amplitude completa.",
        },
        {
          name: "Remada Curvada",
          detail: "Espessura de costas",
          type: "COMPOSTO",
          muscleGroup: "back",
          setsReps: "4 × 6-10",
          defaultSets: 4,
          rest: "2 min",
          notes: "Tronco estável.",
        },
        {
          name: "Puxada Frontal",
          detail: "Largura de dorsal",
          type: "COMPOSTO",
          muscleGroup: "back",
          setsReps: "3 × 8-12",
          defaultSets: 3,
          rest: "90 s",
          notes: "Puxe com cotovelos.",
        },
        {
          name: "Facepull",
          detail: "Deltoide posterior",
          type: "ISOLAMENTO",
          muscleGroup: "shoulders",
          setsReps: "3 × 12-20",
          defaultSets: 3,
          rest: "60 s",
          notes: "Foco em escápulas.",
        },
        {
          name: "Rosca Direta",
          detail: "Bíceps",
          type: "ISOLAMENTO",
          muscleGroup: "biceps",
          setsReps: "3 × 8-12",
          defaultSets: 3,
          rest: "60-90 s",
          notes: "Evite embalo.",
        },
      ],
    },
    {
      splitType: "ppl",
      type: "leg",
      label: "Pernas",
      title: "Pernas",
      icon: PersonSimpleRunIcon,
      badge: "QUADS / POSTERIOR / GLÚTEO",
      focus: "hypertrophy",
      duration: "70-90 min",
      exercises: [
        {
          name: "Agachamento Livre",
          detail: "Pernas completo",
          type: "COMPOSTO",
          muscleGroup: "quads",
          setsReps: "4 × 5-8",
          defaultSets: 4,
          rest: "3 min",
          notes: "Profundidade consistente.",
        },
        {
          name: "Levantamento Terra Romeno",
          detail: "Posterior de coxa",
          type: "COMPOSTO",
          muscleGroup: "hamstrings",
          setsReps: "3 × 6-10",
          defaultSets: 3,
          rest: "2 min",
          notes: "Quadril para trás.",
        },
        {
          name: "Leg Press",
          detail: "Quadríceps",
          type: "COMPOSTO",
          muscleGroup: "quads",
          setsReps: "3 × 10-12",
          defaultSets: 3,
          rest: "2 min",
          notes: "Amplitude completa.",
        },
        {
          name: "Mesa Flexora",
          detail: "Posterior",
          type: "ISOLAMENTO",
          muscleGroup: "hamstrings",
          setsReps: "3 × 10-15",
          defaultSets: 3,
          rest: "60-90 s",
          notes: "Controle excêntrico.",
        },
        {
          name: "Panturrilha em Pé",
          detail: "Panturrilha",
          type: "ISOLAMENTO",
          muscleGroup: "calves",
          setsReps: "4 × 10-15",
          defaultSets: 4,
          rest: "45-60 s",
          notes: "Pausa em alongamento.",
        },
      ],
    },
  ],
}
